# Generated by Django 4.2.5 on 2023-11-11 12:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ItineraryPlan',
            fields=[
                ('ItineraryPlan_id', models.AutoField(primary_key=True, serialize=False)),
                ('ItineraryPlan_title', models.CharField(max_length=100)),
                ('ItineraryPlan_description', models.TextField(blank=True, help_text='Enter the description of this holiday')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryEvent',
            fields=[
                ('ItineraryEvent_id', models.AutoField(primary_key=True, serialize=False)),
                ('itineraryEvent_description', models.TextField(help_text='Enter the description of this event')),
                ('itineraryEvent_datetime', models.DateTimeField()),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('ItineraryPlan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.itineraryplan')),
            ],
        ),
    ]
