# Generated by Django 4.2.5 on 2023-11-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplan',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.profile'),
        ),
    ]
