# Generated by Django 4.2.5 on 2023-11-11 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itinerary', '0004_alter_itineraryplan_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryplan',
            name='username',
        ),
        migrations.AddField(
            model_name='itineraryplan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
