# Generated by Django 4.2.5 on 2023-11-11 22:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_remove_itineraryplan_username_itineraryplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='itineraryevent',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itineraryevent',
            name='lon',
            field=models.FloatField(),
        ),
    ]
