# Generated by Django 4.2.5 on 2023-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_profile_location_alter_itineraryevent_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryevent',
            name='ItineraryEvent_title',
            field=models.CharField(default='Default title', max_length=100),
        ),
        migrations.AlterField(
            model_name='itineraryplan',
            name='ItineraryPlan_title',
            field=models.CharField(default='Default title', max_length=100),
        ),
    ]
