# Generated by Django 4.2.5 on 2023-11-12 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0009_alter_itineraryevent_itineraryevent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryevent',
            name='itineraryEvent_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
