# Generated by Django 4.2.7 on 2024-01-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0011_profile_location_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryplan',
            name='sharedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
