# Generated by Django 4.2.7 on 2024-01-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0012_itineraryplan_sharedstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplan',
            name='sharedStatus',
            field=models.BooleanField(default='Enter User boolean input to publicly share plan or not '),
        ),
    ]
