# Generated by Django 4.2.7 on 2024-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0019_alter_itineraryevent_itineraryevent_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryevent',
            name='ItineraryEvent_title',
            field=models.CharField(default='Default title', max_length=100),
        ),
        migrations.AlterField(
            model_name='itineraryplan',
            name='ItineraryPlan_title',
            field=models.CharField(default='Default title', max_length=100),
        ),
    ]
